#!/bin/bash

# get all available projects
NAMESPACE=$(oc get project | egrep -v '^NAME' | awk '{ print $1}')

#new line
echo ""

export STATUS=Running

while read line 
do
 if [ "$?" > "0" ] 
  then
   echo -e "\033[1;32mcontainer:\033[m ${line}"
   oc exec -t ${line} -- java -version | - 2> /dev/null
 fi

done < <(oc get pods | grep -v NAME | awk -v LIMIT=${STATUS} '($3>=LIMIT) { print $1 }')

#while read line ; do echo project: $line ; oc get pods --namespace=$line | grep -v ^NAME ; done < <(oc get project | grep -v ^NAME | awk '{ print $1 }' | while read line ; do echo $line ; sleep 1 ; done)

